/*
 * 収録データ
 *   w      : 答え（読み）。クイズの正解・一覧の見出しになる
 *   shown  : 作中の表記が w と違う場合（誤記・ウムラウト省略など）。魔女文字はこちらで描く
 *   ja     : 意味・訳
 *   where  : 登場箇所
 *   script : 作中の書体（archaic / modern / musical / latin）。「作中の書体で表示」がオンのとき使う
 *   note   : 補足
 * 作中の文の解読はファンによるもの（出典は各カテゴリの sources）。訳は本アプリでの意訳です。
 */
window.CORPUS = [
  {
    id: 'witch',
    label: '魔女図鑑・魔女',
    desc: 'TVシリーズ公式サイト「魔女図鑑」に掲載の魔女。肩書きと性質は図鑑より。',
    defaultOn: true,
    sources: [{ name: '魔法少女まどか☆マギカ 公式サイト 魔女図鑑', url: 'https://www.madoka-magica.com/tv/special/dic/card1.html' }],
    items: [
      { w: 'GERTRUD', ja: '薔薇園の魔女（性質：不信）', where: '第1〜2話', lang: 'de-name' },
      { w: 'SULEIKA', ja: '暗闇の魔女（性質：妄想）', where: '図鑑のみ（未登場）', lang: 'de-name' },
      { w: 'CHARLOTTE', ja: 'お菓子の魔女（性質：執着）', where: '第3話', lang: 'de-name' },
      { w: 'KIRSTEN', ja: 'ハコの魔女の本名（性質：憧憬）', where: '第4話', lang: 'de-name' },
      { w: 'ELLY', ja: 'ハコの魔女のハンドルネーム H.N.エリー', where: '第4話', lang: 'de-name' },
      { w: 'ALBERTINE', ja: '落書きの魔女（性質：無知）', where: '図鑑のみ（未登場）', lang: 'de-name' },
      { w: 'GISELA', ja: '銀の魔女（性質：自由）', where: '第7話', lang: 'de-name' },
      { w: 'ELSA MARIA', ja: '影の魔女（性質：独善）', where: '第7〜8話', lang: 'de-name' },
      { w: 'UHRMANN', ja: '犬の魔女（性質：渇望）', where: '図鑑のみ（未登場）', lang: 'de-name' },
      { w: 'OKTAVIA VON SECKENDORFF', ja: '人魚の魔女（性質：恋慕）', where: '第9〜10話', lang: 'de-name' },
      { w: 'IZABEL', ja: '芸術家の魔女（性質：虚栄）', where: '第10話', lang: 'de-name' },
      { w: 'PATRICIA', ja: '委員長の魔女（性質：傍観）', where: '第10話', lang: 'de-name' },
      { w: 'ROBERTA', ja: '鳥かごの魔女（性質：憤怒）', where: '第10話', lang: 'de-name' },
      { w: 'KRIEMHILD GRETCHEN', ja: '救済の魔女（性質：慈悲）', where: '第10話', lang: 'de-name' },
      { w: 'WALPURGISNACHT', ja: '舞台装置の魔女・通称ワルプルギスの夜（性質：無力）', where: '第11〜12話', lang: 'de-name' }
    ]
  },
  {
    id: 'familiar',
    label: '魔女図鑑・手下',
    desc: '魔女図鑑に掲載の手下（使い魔）。役割は図鑑より。名前はファンによる魔女文字の解読。',
    defaultOn: false,
    sources: [{ name: '魔法少女まどか☆マギカ 公式サイト 魔女図鑑', url: 'https://www.madoka-magica.com/tv/special/dic/card1.html' }],
    items: [
      { w: 'ANTHONY', ja: '薔薇園の魔女の手下（役割：造園）', lang: 'de-name' },
      { w: 'ADELBERT', ja: '薔薇園の魔女の手下（役割：警戒）', lang: 'de-name' },
      { w: 'ULLA', ja: '暗闇の魔女の手下（役割：夢）', lang: 'de-name' },
      { w: 'PYOTR', ja: 'お菓子の魔女の手下（役割：チーズを探すこと）', lang: 'name' },
      { w: 'DANIYELLA', ja: 'ハコの魔女の手下（役割：運搬）', lang: 'de-name' },
      { w: 'JENNIFER', ja: 'ハコの魔女の手下（役割：運搬）', lang: 'de-name' },
      { w: 'ANJA', ja: '落書きの魔女の手下（役割：童心）', lang: 'de-name' },
      { w: 'DORA', ja: '銀の魔女の手下（役割：主張）', lang: 'de-name' },
      { w: 'SEBASTIAN', ja: '影の魔女の手下（役割：妄信）', lang: 'de-name' },
      { w: 'BARTELS', ja: '犬の魔女の手下（役割：インテリア）', lang: 'de-name' },
      { w: 'HOLGER', ja: '人魚の魔女の手下（役割：演奏）', lang: 'de-name' },
      { w: 'KLARISSA', ja: '人魚の魔女の手下（役割：バックダンサー）', lang: 'de-name' },
      { w: 'MICHAELA', ja: '芸術家の魔女の手下（役割：作品）', lang: 'de-name' },
      { w: 'GIUSEPPE MARCELLO', ja: '委員長の魔女の手下（役割：クラスメイト）', lang: 'name' },
      { w: 'GOTZ', ja: '鳥かごの魔女の手下（役割：軽薄無思慮）', lang: 'de-name' }
    ]
  },
  {
    id: 'tv',
    scene: true,
    label: 'TV版の文',
    desc: 'TVシリーズの結界などに書かれた魔女文字。',
    defaultOn: true,
    sources: [{ name: 'Puella Magi Wiki – Witch Runes（各話の解読表）', url: 'https://wiki.puella-magi.net/Category:Witch_Runes' }],
    items: [
      { w: 'PROLOG IM HIMMEL 2011', ja: '天上の序曲 2011', where: '第1話 冒頭', note: '『ファウスト』第一部の場面名', lang: 'de' },
      { w: 'BEKÄMPFE SCHÄDLICHE INSEKTEN', ja: '害虫を駆除せよ', where: '第1話 薔薇園の魔女の結界', lang: 'de' },
      { w: 'KEIN DURCHGANG', ja: '通り抜け禁止', where: '第1話 薔薇園の魔女の結界', lang: 'de' },
      { w: 'KEIN DURCHGANG ZUTRITT VERBOTEN', ja: '通り抜け禁止　立入禁止', where: '第1話 薔薇園の魔女の結界', lang: 'de' },
      { w: 'KEIN DURCHGANG ZUTRITT VERBOTEN', ja: '通り抜け禁止　立入禁止（音符の書体）', where: '第1話 薔薇園の魔女の結界', script: 'musical', lang: 'de' },
      { w: 'DAS SIND MIR UNBEKANNTE BLUMEN', ja: 'これは知らない花だ', where: '第1話 薔薇園の魔女の結界', script: 'modern', lang: 'de' },
      { w: 'JA SIE SIND MIR AUCH UNBEKANNT', ja: 'ええ、わたしも知らない', where: '第1話 アントニーの詩（BD版）', lang: 'de' },
      { w: 'SCHNEIDEN WIR SIE AB', ja: '切り落としてしまおう', where: '第1話 アントニーの詩（BD版）', lang: 'de' },
      { w: 'DIE ROSEN SCHENKEN WIR UNSRER KÖNIGIN', ja: '薔薇は女王さまに捧げよう', where: '第1話 アントニーの詩（BD版）', lang: 'de' },
      { w: 'UND DIE SCHLECHTEN BLUMEN STEIGEN AUF DIE GUILLOTINE', ja: 'そして悪い花はギロチン台へ', where: '第1話 アントニーの詩（BD版）', lang: 'de' },
      { w: 'JA SCHNEIDE SIE AB', ja: 'そう、切り落とせ', where: '第1話 アントニーの詩（BD版）', lang: 'de' },
      { w: 'JA SCHNEIDE SIE HERAUS', ja: 'そう、切り取ってしまえ', where: '第1話 アントニーの詩（BD版）', lang: 'de' },
      { w: 'SCHNEIDEN WIRS AB', ja: '切り落としちゃおう', where: '第1話（BD版）', lang: 'de' },
      { w: 'SCHNEIDEN WIR ÜBERFLÜSSIGE ÄSTE HERAUS', shown: 'SCHNEIDEN WIR UDERFLUSSIGE ASTE HERAUS', ja: '余分な枝を切り落とそう', where: '第1話 薔薇園の魔女の結界', note: '作中の表記は UDERFLUSSIGE ASTE', lang: 'de' },
      { w: 'STUTZEN FÜR DIE NEUEN ÄSTE', shown: 'STUTZEN FUR DIE NEUEN ASTE', ja: '新しい枝のために刈り込もう', where: '第1話 薔薇園の魔女の結界', lang: 'de' },
      { w: 'DIE BLÜHENDEN ROSEN SOLLEN DER KÖNIGIN SOFORT GESCHENKT SEIN', shown: 'DAI BLUHENDEN ROSEN SOLLEN DER KONIGIN SOFORT GESCHENKT SEIN', ja: '咲いた薔薇はすぐに女王さまへ捧げるべし', where: '第1話 薔薇園の魔女の結界', script: 'modern', note: '作中の表記は DAI BLUHENDEN … KONIGIN', lang: 'de' },
      { w: 'MAN SOLL EINMAL MIT JA ANTWORTEN UND ORDENTLICH IN REIHEN MARSCHIEREN', shown: 'MAN SOLL EINMAJ MIT JA ANTWORTEN AND ORDNTLICH LN REIHEN MARSCHIEREN', ja: '返事は一度「はい」と、きちんと列を作って行進すべし', where: '第1話 薔薇園の魔女の結界', script: 'modern', note: '作中の表記には誤記が多い', lang: 'de' },
      { w: 'DU MUßT VERSTEHN AUS EINS MACH ZEHN UND ZWEI LAß GEHN UND DREI MACH GLEICH', ja: 'わかるかい、一を十とし、二は放っておき、三はそのまま…', where: '第1話 薔薇園の魔女の結界', note: '『ファウスト』の「魔女の九九」', lang: 'de' },
      { w: 'TASUKE NI KITA YO', ja: '助けに来たよ（日本語ローマ字）', where: '第1話', script: 'modern', lang: 'ja' },
      { w: 'MOERO', ja: '燃えろ（日本語ローマ字）', where: '第1話 消火器', script: 'modern', lang: 'ja' },
      { w: 'MAMI', ja: 'マミ', where: '第3話', lang: 'name' },
      { w: 'ICH MAG KEINE NARREN', ja: '愚か者は嫌いだ', where: '第4話 ハコの魔女の結界', lang: 'de' },
      { w: 'ICH WILL NICHT ARBEITEN', ja: '働きたくない', where: '第4話 ハコの魔女の結界', lang: 'de' },
      { w: 'ANJA WACHSMALSTIFT', ja: 'アーニャ　クレヨン', where: '第5話（BD版）', lang: 'de' },
      { w: 'FIN', ja: 'おしまい（フランス語・スペイン語）', where: '第5話', lang: 'other' },
      { w: 'HOMURA', ja: 'ほむら（ソウルジェムの指輪）', where: '第7話', lang: 'name' },
      { w: 'SAYAKA', ja: 'さやか（ソウルジェムの指輪）', where: '第7〜8話', lang: 'name' },
      { w: 'KYOKO', ja: '杏子（ソウルジェムの指輪）', where: '第7話', lang: 'name' },
      { w: 'TEMPESTOSO', ja: '嵐のように激しく（音楽用語）', where: '第8話', script: 'musical', lang: 'other' },
      { w: 'AFFETTUOSO', ja: '愛情をこめて（音楽用語）', where: '第8話', script: 'musical', lang: 'other' },
      { w: 'OKTAVIA VON SECKENDORFF', ja: 'オクタヴィア・フォン・ゼッケンドルフ', where: '第9話 人魚の魔女の結界', script: 'musical', lang: 'de-name' },
      { w: 'HOPE SCHICKSAL', ja: '希望　運命', where: '第9話 人魚の魔女の結界', script: 'musical', lang: 'mix' },
      { w: 'LOOK AT ME', ja: 'わたしを見て', where: '第9話', lang: 'en' },
      { w: 'KYOSUKE CLASSIC CONCERT', ja: '恭介 クラシックコンサート', where: '第9話', script: 'musical', lang: 'en' },
      { w: 'CON AMORE', ja: '愛をこめて（音楽用語）', where: '第9話', script: 'musical', lang: 'other' },
      { w: 'ISADEL', ja: 'イザベル（IZABEL の誤記）', where: '第10話', lang: 'de-name' },
      { w: 'RINDFLEISCH', ja: '牛肉', where: '第11話', lang: 'de' },
      { w: 'SCHWEIN', ja: '豚', where: '第11話', lang: 'de' },
      { w: 'VIEH', ja: '家畜', where: '第11話', lang: 'de' },
      { w: 'FLEISCH', ja: '肉', where: '第11話', lang: 'de' },
      { w: 'MUH MUHTEN', ja: 'モーと鳴いた', where: '第11話', lang: 'de' },
      { w: 'CHICKEN', shown: 'CHCIKEN', ja: 'チキン（英語。作中は綴り違い）', where: '第11話', lang: 'en' },
      { w: 'HÖRBEISPIEL', ja: '試聴サンプル', where: '第11話', lang: 'de' },
      { w: 'MADOKA', ja: 'まどか', where: '第11話', lang: 'name' },
      { w: 'QBEY', ja: 'キュゥべえ', where: '第11話', lang: 'name' },
      { w: 'WALPURGIS NACHT', ja: 'ワルプルギスの夜', where: '第11話', lang: 'de' },
      { w: 'OSHIMAI', ja: 'おしまい', where: '第12話', lang: 'ja' },
      { w: 'PUELLA MAGI MADOKA MAGIKA', ja: '魔法少女まどか☆マギカ', where: '第12話', lang: 'other' }
    ]
  },
  {
    id: 'movie',
    scene: true,
    label: '劇場版［前編・後編］',
    desc: '劇場版『始まりの物語』『永遠の物語』とコンセプトムービー。',
    defaultOn: false,
    sources: [{ name: 'Puella Magi Wiki – Witch Runes/Beginnings and Eternal', url: 'https://wiki.puella-magi.net/Witch_Runes/Beginnings_and_Eternal' }],
    items: [
      { w: 'WALPURGIS NACHT PROLOG IM HIMMEL 2013', ja: 'ワルプルギスの夜　天上の序曲 2013', where: '劇場版 冒頭', lang: 'de' },
      { w: 'WO IST DER KÄSE', shown: 'WO IST DER KASE?', ja: 'チーズはどこ？', where: '劇場版 お菓子の魔女の結界', lang: 'de' },
      { w: 'I LOVE KÄSE', shown: 'I LOVE KASE!', ja: 'チーズ大好き！', where: '劇場版 お菓子の魔女の結界', lang: 'mix' },
      { w: 'MEIN NAME IST ELLY', ja: 'わたしの名前はエリー', where: '劇場版 ハコの魔女', lang: 'de' },
      { w: 'HALLO NICE TO MEET', shown: 'HALL. NICE TO MEET.', ja: 'こんにちは、はじめまして', where: '劇場版 ハコの魔女', lang: 'en' },
      { w: 'DESIDERANTES AFFECTIBUS', ja: '至上の熱意をもって（ラテン語）', where: '劇場版', lang: 'other' },
      { w: 'DEN LILLE HAVFRUE', ja: '人魚姫（デンマーク語）', where: '劇場版 人魚の魔女', script: 'musical', lang: 'other' },
      { w: 'EIEN NI SITE MAHOU NARU KOTOWARI NO MOTONI', ja: '永遠にして、魔法なる理のもとに', where: 'コンセプトムービー', lang: 'ja' }
    ]
  },
  {
    id: 'rebellion',
    scene: true,
    label: '叛逆の物語',
    desc: '劇場版『叛逆の物語』に登場する魔女文字。ネタバレを含みます。',
    defaultOn: false,
    sources: [
      { name: 'Puella Magi Wiki – Witch Runes/Rebellion', url: 'https://wiki.puella-magi.net/Witch_Runes/Rebellion' }
    ],
    items: [
      { w: 'SORE GA MAHOU SYOUJO', shown: 'SORE GA MA HOU SYOUJO', ja: 'それが魔法少女', where: '冒頭の壁画', lang: 'ja' },
      { w: 'KISEKI', shown: 'KI SE KI', ja: '奇跡', where: '冒頭の壁画', lang: 'ja' },
      { w: 'KYUUSAI', shown: 'KYU USAI', ja: '救済', where: '冒頭の壁画', lang: 'ja' },
      { w: 'ENKAN NO KOTOWARI', shown: 'ENKAN NO KOTO WARI', ja: '円環の理', where: '冒頭の壁画', lang: 'ja' },
      { w: 'YUME', shown: 'YU ME', ja: '夢', where: '冒頭の壁画', lang: 'ja' },
      { w: 'SYOUMETU', shown: 'SYOU METU', ja: '消滅', where: '教会の壁画', lang: 'ja' },
      { w: 'ES IST SCHON MORGEN', ja: 'もう朝だ', where: '冒頭ナレーション', lang: 'de' },
      { w: 'HOMU LILLY', ja: 'ホムリリィ', where: 'ナイトメアのタグ ほか', lang: 'de-name' },
      { w: 'MADE IN CABINET', ja: 'キャビネット製', where: 'ナイトメアのタグの裏面', lang: 'en' },
      { w: 'WHO AM I', shown: 'WHO AM I?', ja: 'わたしは誰？', where: 'ナイトメアが逃げ込む扉', lang: 'en' },
      { w: 'DOES NOT MATTER THE LETS DANCE NOW', shown: "DOES NOT MATTER THE LET'S DANCE NOW", ja: '気にしないで、さあ踊ろう', where: 'ナイトメアが逃げ込む扉', lang: 'en' },
      { w: 'YAGINOKONOYUME', ja: 'やぎのこのゆめ（仁美のナイトメア）', where: '仁美ナイトメア戦', lang: 'ja' },
      { w: 'ZU MEISTERN WIR SIND GELANGWEILT', ja: 'ご主人さまへ　わたしたちは退屈している', where: 'ほむらの変身シーン', lang: 'de' },
      { w: 'ICH TÖTE MICH', shown: 'LCH TÖTE MICH', ja: 'わたしはわたしを殺す', where: 'ほむらの変身シーン', note: '作中の表記は LCH', lang: 'de' },
      { w: 'SIE VERHERRLICHEN DEN TOD', shown: 'SIE VERHERRLICHEN DEN TODV', ja: '彼らは死を讃える', where: 'ほむらの変身シーン', note: '作中の表記は TODV', lang: 'de' },
      { w: 'REVERIE', ja: '夢想', where: 'ナイトメア結界の背景', script: 'musical', lang: 'other' },
      { w: 'BEBES SWEETS', shown: "BEBE'S SWEETS", ja: 'べべのお菓子', where: 'ビルに投影された広告', lang: 'en' },
      { w: 'BEBE JUICE 100%', ja: 'べべジュース 100%', where: 'ビルに投影された広告', lang: 'en' },
      { w: 'BEBECHOCO SHINUHODO AMAI', ja: 'べべチョコ　死ぬほど甘い', where: 'ビルに投影された広告', lang: 'ja' },
      { w: 'COSMIC ICE', ja: 'コズミックアイス', where: 'ビルに投影された広告', lang: 'en' },
      { w: 'ZETUBOUMAMIRE NUMENUMESHITA KUTIZAWARI', ja: '絶望まみれ　ぬめぬめした口ざわり', where: 'ビルに投影された広告', lang: 'ja' },
      { w: 'ICH MÖCHTE UNSEREN KUNDEN DANKEN', shown: 'LCH MÖCHTE UNSEREN KUNDEN DANKEN', ja: 'お客様に感謝いたします', where: 'ゴンドラのシーン', note: '作中の表記は LCH', lang: 'de' },
      { w: 'HITORI BOCCHI NI ONIAI', ja: 'ひとりぼっちにお似合い', where: 'クララドールズ「アイ」のパッケージ', lang: 'ja' },
      { w: 'WER TRÄUMT', shown: 'WER TRÄUMT?', ja: '夢を見ているのは誰？', where: '船が燃えるシーン ほか', lang: 'de' },
      { w: 'WER HAT GETRÄUMT', shown: 'WER HAT GETRÄUMT?', ja: '夢を見ていたのは誰？', where: 'エンディング前（BD版）', lang: 'de' },
      { w: 'HANGYAKU', shown: 'HANG YAKU', ja: '叛逆', where: 'ゲームセンターの看板', lang: 'ja' },
      { w: 'SIE', ja: '彼女／あなた', where: '暗転後の画面', lang: 'de' },
      { w: 'DEKISOKONAI NARISOKONAI MANUKENASUGATA', ja: 'できそこない　なりそこない　まぬけな姿', where: 'ホムリリィの魔女カード', lang: 'ja' },
      { w: 'KURUMIWARINOMAJO', ja: 'くるみ割りの魔女', where: 'ホムリリィの魔女カード', lang: 'ja' },
      { w: 'SEISITUWA JIKOKANKETU', ja: '性質は自己完結', where: 'ホムリリィの魔女カード', lang: 'ja' },
      { w: 'ITUMOOMAEHA WARAIMONO', ja: 'いつもお前は笑い者', where: 'ホムリリィの魔女カード', lang: 'ja' },
      { w: 'KANASIOMIDE', ja: '悲しい思い出（「おもいで」の脱字とされる）', where: 'ホムリリィの帽子', lang: 'ja' },
      { w: 'JYOUNETU', ja: '情熱', where: 'ホムリリィの帽子', lang: 'ja' },
      { w: 'AKIRAME', ja: 'あきらめ', where: 'ホムリリィの帽子', lang: 'ja' },
      { w: 'OMOUHA ANATA HITORI', ja: '想うはあなた一人', where: 'ホムリリィの帽子', lang: 'ja' },
      { w: 'MATAAUHIWO TANOSIMINI', ja: 'また会う日を楽しみに', where: 'ホムリリィの帽子', lang: 'ja' },
      { w: 'SAIKAI', ja: '再会', where: 'ホムリリィの帽子', lang: 'ja' },
      { w: 'DOKURITU', ja: '独立', where: 'ホムリリィの帽子', lang: 'ja' },
      { w: 'LILLI', ja: 'リリィ（LILLY の誤記とされる）', where: 'ホムリリィの帽子の中心', lang: 'de-name' },
      { w: 'HOMULILLY', ja: 'ホムリリィ', where: 'ダークオーブのイヤーカフス', note: '作中では HOMUL まで読める', lang: 'de-name' },
      { w: 'MAHOU SHOUJO', ja: '魔法少女', where: '魔法少女のレシピの見出し（なぎさの変身）', lang: 'ja' },
      { w: 'GIRL SOUL JEM SUGAR PEPPER SAUCE', ja: '少女　ソウルジェム　砂糖　胡椒　ソース', where: '魔法少女のレシピ', lang: 'en' },
      { w: 'DREAM HOPE INNOCENCE', ja: '夢　希望　無垢', where: '魔法少女のレシピ', lang: 'en' },
      { w: 'A LITTLE QUANTITY', shown: '(A LITTLE QUANTITY)', ja: '少々', where: '魔法少女のレシピ', lang: 'en' },
      { w: 'SWEET', ja: '甘い', where: 'レシピ横のべべの吹き出し', lang: 'en' },
      { w: 'PLEASE BE CAREFUL ABOUT THE HANDLING OF THE MAGIC', ja: '魔法の取り扱いにはご注意ください', where: '魔法少女のレシピ', lang: 'en' },
      { w: 'CHARLOTTE', ja: 'シャルロッテ', where: 'なぎさの周りの魔法陣', lang: 'de-name' },
      { w: 'MAMI', ja: 'マミ', where: 'マミの変身シーン', lang: 'name' },
      { w: 'SAYAKA', ja: 'さやか', where: 'さやかの変身シーン', lang: 'name' },
      { w: 'CLALA DOLLS', ja: '偽街の子供達（役割：泣き屋）', where: '魔女図鑑（叛逆の物語）', lang: 'name' },
      { w: 'LOTTE', ja: 'くるみ割りの魔女の手下（役割：刑の執行）', where: '魔女図鑑（叛逆の物語）', lang: 'de-name' },
      { w: 'LUISELOTTE', ja: 'くるみ割りの魔女の手下（役割：ネズミの駆除）', where: '魔女図鑑（叛逆の物語）', lang: 'de-name' },
      { w: 'LILIA', ja: 'くるみ割りの魔女の手下（役割：咀嚼）', where: '魔女図鑑（叛逆の物語）', lang: 'de-name' },
      { w: 'LIESE', ja: 'くるみ割りの魔女の手下（役割：凶報）', where: '魔女図鑑（叛逆の物語）', lang: 'de-name' },
      { w: 'DAS EWIG WEIBLICHE', ja: '永遠に女性的なるもの', where: '円環の理の紋章', note: '『ファウスト』の結びの句から', lang: 'de' },
      { w: 'DIE EWIGE WIEDERKEHR DES GLEICHEN', ja: '同じものの永劫回帰（ニーチェ）', where: 'パラソルの柄（BD版）', lang: 'de' },
      { w: 'OSHIMAI', ja: 'おしまい', where: 'エンディング', lang: 'ja' }
    ]
  },
  {
    id: 'rising',
    scene: true,
    label: 'ワルプルギスの廻天',
    desc: '劇場版『ワルプルギスの廻天』に登場する魔女文字。ネタバレを含みます。',
    defaultOn: false,
    spoiler: true,
    sources: [
      { name: 'Puella Magi Wiki – Witch Runes/Walpurgisnacht Rising', url: 'https://wiki.puella-magi.net/Witch_Runes/Walpurgisnacht_Rising' }
    ],
    items: [
      { w: 'COMMEDIA', ja: '喜劇（イタリア語）', where: '冒頭と結末', script: 'latin', note: 'ダンテ『神曲』の原題から', lang: 'other' },
      { w: 'EVIL EYE', ja: '邪視', where: 'ドローンカメラ', script: 'latin', lang: 'en' },
      { w: 'HELP YOU', ja: 'ヘルプ・ユー', where: '旗', script: 'latin', lang: 'en' },
      { w: 'NOT FOUND', ja: '見つかりません', where: 'さやかの包帯', script: 'latin', note: 'さやかの部屋番号 404 と重なる', lang: 'en' },
      { w: 'ANONYMOUS', ja: '名無し', where: 'ワスの指輪', script: 'archaic', lang: 'en' },
      { w: 'LIMBO', ja: '辺獄', where: '名塚底根', script: 'archaic', note: '『神曲』地獄篇の第一圏', lang: 'other' },
      { w: 'PER ME SI VA NE LA CITTA DOLENTE', ja: 'われを過ぎんとする者は憂いの都へ', where: '名塚底根の入口', script: 'archaic', note: '『神曲』地獄篇 第3歌・地獄の門の銘（1行目）', lang: 'other' },
      { w: 'PER ME SI VA NE LETTERNO DOLORE', ja: 'われを過ぎんとする者は永劫の苦しみへ', where: '名塚底根の入口', script: 'archaic', note: '同・2行目（原文は l’etterno）', lang: 'other' },
      { w: 'PER ME SI VA TRA LA PERDUTA GENTE', ja: 'われを過ぎんとする者は滅びの民のもとへ', where: '名塚底根の入口', script: 'archaic', note: '同・3行目', lang: 'other' },
      { w: 'WITCHES', ja: '魔女たち', script: 'archaic', lang: 'en' },
      { w: 'KRIEMHILD GRETCHEN', ja: 'クリームヒルト・グレートヒェン', where: 'ワスが使う封印', script: 'archaic', lang: 'de-name' },
      { w: 'GOOD BEAR', ja: 'いい子のクマ', where: 'セルマのコアの背景', lang: 'en' },
      { w: 'AWAKING', ja: '目覚め', where: 'ニセ見滝原が崩れる場面', lang: 'en' },
      { w: 'DU BIST SO SCHÖN FLIEßE DOCH', ja: 'お前は美しい、流れよ！', where: '終盤', note: '『ファウスト』の「時よ止まれ」の反転', lang: 'de' }
    ]
  },
  {
    id: 'name',
    label: '登場人物',
    desc: '主な登場人物の名前（ローマ字）。',
    defaultOn: true,
    items: [
      { w: 'MADOKA', ja: 'まどか', lang: 'name' },
      { w: 'HOMURA', ja: 'ほむら', lang: 'name' },
      { w: 'SAYAKA', ja: 'さやか', lang: 'name' },
      { w: 'MAMI', ja: 'マミ', lang: 'name' },
      { w: 'KYOKO', ja: '杏子', lang: 'name' },
      { w: 'KYUBEY', ja: 'キュゥべえ', lang: 'name' },
      { w: 'HITOMI', ja: '仁美', lang: 'name' },
      { w: 'KYOSUKE', ja: '恭介', lang: 'name' },
      { w: 'TATSUYA', ja: 'タツヤ', lang: 'name' },
      { w: 'NAGISA', ja: 'なぎさ', lang: 'name' },
      { w: 'BEBE', ja: 'べべ', lang: 'name' },
      { w: 'HOMULILLY', ja: 'ホムリリィ', lang: 'de-name' }
    ]
  },
  {
    id: 'german',
    label: 'ドイツ語の単語',
    desc: '作中の文によく出てくる、または予測に役立つドイツ語。',
    defaultOn: true,
    items: [
      { w: 'HEXE', ja: '魔女', lang: 'de' },
      { w: 'MAGIE', ja: '魔法', lang: 'de' },
      { w: 'HOFFNUNG', ja: '希望', lang: 'de' },
      { w: 'VERZWEIFLUNG', ja: '絶望', lang: 'de' },
      { w: 'WUNSCH', ja: '願い', lang: 'de' },
      { w: 'SEELE', ja: '魂', lang: 'de' },
      { w: 'TRAUM', ja: '夢', lang: 'de' },
      { w: 'SCHICKSAL', ja: '運命', lang: 'de' },
      { w: 'FREUNDIN', ja: '友だち（女性）', lang: 'de' },
      { w: 'ENGEL', ja: '天使', lang: 'de' },
      { w: 'ZEIT', ja: '時間', lang: 'de' },
      { w: 'NACHT', ja: '夜', lang: 'de' },
      { w: 'MORGEN', ja: '朝／明日', lang: 'de' },
      { w: 'STERN', ja: '星', lang: 'de' },
      { w: 'ROSE', ja: '薔薇', lang: 'de' },
      { w: 'BLUMEN', ja: '花（複数）', lang: 'de' },
      { w: 'KÖNIGIN', ja: '女王', lang: 'de' },
      { w: 'KUCHEN', ja: 'ケーキ', lang: 'de' },
      { w: 'KÄSE', ja: 'チーズ', lang: 'de' },
      { w: 'LIEBE', ja: '愛', lang: 'de' },
      { w: 'TOD', ja: '死', lang: 'de' },
      { w: 'GÖTTIN', ja: '女神', lang: 'de' },
      { w: 'WUNDER', ja: '奇跡', lang: 'de' },
      { w: 'EWIGKEIT', ja: '永遠', lang: 'de' },
      { w: 'ICH', ja: 'わたし', lang: 'de' },
      { w: 'NICHT', ja: '〜ない', lang: 'de' },
      { w: 'KEIN', ja: 'ひとつも〜ない', lang: 'de' },
      { w: 'UND', ja: 'そして', lang: 'de' },
      { w: 'WER', ja: '誰', lang: 'de' },
      { w: 'WO IST', ja: '〜はどこ', lang: 'de' },
      { w: 'VERBOTEN', ja: '禁止', lang: 'de' },
      { w: 'SCHNEIDEN', ja: '切る', lang: 'de' }
    ]
  },
  {
    id: 'faust',
    label: '『ファウスト』の一節',
    desc: '作品のモチーフになっているゲーテ『ファウスト』から（作中に登場するとは限りません）。',
    defaultOn: false,
    items: [
      { w: 'VERWEILE DOCH DU BIST SO SCHÖN', ja: '時よ止まれ、お前は美しい', lang: 'de' },
      { w: 'MEINE RUH IST HIN MEIN HERZ IST SCHWER', ja: 'わたしの安らぎは消え、心は重い（グレートヒェン）', lang: 'de' },
      { w: 'ICH BIN DER GEIST DER STETS VERNEINT', ja: 'わたしは常に否定する霊（メフィストフェレス）', lang: 'de' },
      { w: 'DAS EWIG WEIBLICHE ZIEHT UNS HINAN', ja: '永遠に女性的なるものが、われらを引き上げる', lang: 'de' },
      { w: 'ES IRRT DER MENSCH SOLANG ER STREBT', ja: '人は努める限り迷うもの', lang: 'de' }
    ]
  }
];
